steps:
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - name: node
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "VITE_API_URL=${_API_URL}"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-east2-docker.pkg.dev/parknexus-440604/park-nexus-images/admin",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-east2-docker.pkg.dev/parknexus-440604/park-nexus-images/admin",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "admin",
        "--image",
        "asia-east2-docker.pkg.dev/parknexus-440604/park-nexus-images/admin",
        "--region",
        "asia-east1",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _API_URL: ""
images:
  - asia-east2-docker.pkg.dev/parknexus-440604/park-nexus-images/admin
availableSecrets:
  secretManager:
    - versionName: projects/1030597876955/secrets/github/versions/1
      env: "SSH_KEY"
